### ISSUE TITLE
[Insight] Form types should be in Form/Type folders - in Form, line 0

### ISSUE THREAD

**Issue by jonny-no1** [fourlabsldn/GmailDoctrineBundle#4]
**[in Form](https://github.com/fourlabsldn/GmailDoctrineBundle/blob/b7548b48c36ef22d667db370958134810dbd1f2e/Form#L0)**

> A form type has been found outside Form/Type folder

```

Form/
├── Type/
├── OutgoingEmailType.php
└── SyncSettingType.php
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/3ed528cf-1d9b-4241-b91a-90eba601f5d4/analyses/1)_

**Comment by galeaspablo** [comment]
Solved with 1431bc35c32fc7c7bd3aadb9ad1898d0c53a14c5
